def main():
    lyrics = load_lyrics()
    cleaned_lyrics = utils.clean_lyrics(lyrics)
    tokens = utils.tokenize_lyrics(cleaned_lyrics)
    content_analysis = la.analyze_content(tokens)
    sentiment_analysis = la.analyze_sentiment(cleaned_lyrics)
    theme_analysis = la.analyze_theme(cleaned_lyrics)
    word_frequency = la.analyze_word_frequency(tokens)
    rhyme_scheme = la.analyze_rhyme_scheme(tokens)
    print("Content Analysis:", content_analysis)
    print("Sentiment Analysis:", sentiment_analysis)
    print("Theme Analysis:", theme_analysis)
    print("Word Frequency:", word_frequency)
    print("Rhyme Scheme:", rhyme_scheme)
    vz.generate_word_cloud(word_frequency)
    vz.plot_sentiment_chart(sentiment_analysis)
    vz.plot_rhyme_scheme_chart(rhyme_scheme)