def main():
    planner = BudgetPlanner()
    planner.add_income("Salary", 5000)
    planner.add_income("Freelance", 1500)
    planner.add_expense("Rent", 1200)
    planner.add_expense("Groceries", 300)
    planner.set_savings_goal(10000)
    planner.generate_recommendations()
    planner.track_spending()
    planner.visualize_progress()