def main():
    db = Database()
    db.connect()
    # Sample data
    emp1 = Employee(1, "John Doe", "Engineering", "Software Engineer")
    emp2 = Employee(2, "Jane Smith", "Marketing", "Marketing Manager")
    goal1 = PerformanceGoal(1, 1, "Complete project X", "2023-01-01", "2023-06-01")
    goal2 = PerformanceGoal(2, 2, "Increase sales by 20%", "2023-01-01", "2023-12-31")
    eval1 = PerformanceEvaluation(1, 1, 101, "2023-06-01", 85, "Good job on project X")
    eval2 = PerformanceEvaluation(2, 2, 102, "2023-12-31", 90, "Excellent sales performance")
    report1 = PerformanceReport(1, 1, "2023-06-01", [goal1], [eval1])
    report2 = PerformanceReport(2, 2, "2023-12-31", [goal2], [eval2])
    emp1.set_performance_goal(goal1)
    emp2.set_performance_goal(goal2)
    emp1.conduct_evaluation(eval1)
    emp2.conduct_evaluation(eval2)
    emp1.generate_report(report1)
    emp2.generate_report(report2)
    # Save reports to database
    db.save_report(report1)
    db.save_report(report2)
    # Fetch and print reports from database
    fetched_report1 = db.fetch_report(1)
    fetched_report2 = db.fetch_report(2)
    print(fetched_report1.generate_report())
    print(fetched_report2.generate_report())
    db.disconnect()