def generate_scatter_plot(self, data):
        labels = list(data.keys())
        sizes = list(data.values())
        plt.figure(figsize=(10, 6))
        plt.scatter(labels, sizes, color=f'red')
        plt.xlabel(f'Categories')
        plt.ylabel(f'Amount')
        plt.title(f'Budget Breakdown - Scatter Plot')
        plt.grid(True)
        plt.xticks(rotation=45, ha=f'right')
        plt.tight_layout()
        plt.show()