def main_menu():
    print("\n=== BudgetTrackerPro ===")
    print("1. Add Income")
    print("2. Add Expense")
    print("3. Set Budget Goal")
    print("4. Check Budget Goal")
    print("5. Add Reminder")
    print("6. View Budget Visualization")
    print("7. Logout")
    print("0. Exit")