def generate_line_chart(self, data):
        labels = list(data.keys())
        sizes = list(data.values())
        plt.figure(figsize=(10, 6))
        plt.plot(labels, sizes, marker='o', linestyle='-', color='green')
        plt.xlabel('Categories')
        plt.ylabel('Amount')
        plt.title('Budget Trend - Line Chart')
        plt.grid(True)
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.show()