def main():
    task_manager = TaskManager()
    time_blocker = TimeBlocker()
    priority_manager = PriorityManager()
    progress_tracker = ProgressTracker()
    reminder_system = ReminderSystem()
    report_generator = ReportGenerator()
    user_interface = UserInterface()
    # Example usage
    task_manager.add_task("Complete project", "2023-10-10", "2023-10-15")
    time_blocker.allocate_time("Complete project", "2023-10-11 09:00", "2023-10-11 11:00")
    priority_manager.set_priority("Complete project", "High")
    progress_tracker.update_progress("Complete project", 50)
    reminder_system.set_reminder("Complete project", "2023-10-11 08:00")
    report = report_generator.generate_report()
    user_interface.display_schedule()