def main():
    expense_manager = ExpenseManager()
    category_manager = CategoryManager()
    budget_manager = BudgetManager()
    receipt_manager = ReceiptManager()
    report_generator = ReportGenerator(expense_manager, receipt_manager)
    trend_analyzer = TrendAnalyzer(expense_manager)
    # Example usage
    category_manager.add_category("Travel")
    category_manager.add_category("Office Supplies")
    expense_manager.add_expense("Flight to NYC 2023-10-01", "Travel", 300.00)
    expense_manager.add_expense("Hotel Stay 2023-10-05", "Travel", 500.00)
    expense_manager.add_expense("Printer Ink 2023-10-02", "Office Supplies", 50.00)
    budget_manager.set_budget("Travel", 1000.00)
    budget_manager.set_budget("Office Supplies", 200.00)
    receipt_manager.upload_receipt("Flight to NYC 2023-10-01", "receipt1.jpg")
    receipt_manager.upload_receipt("Printer Ink 2023-10-02", "receipt2.jpg")
    report_generator.generate_pdf_report()
    report_generator.generate_csv_report()
    # Analyze trends
    monthly_trends = trend_analyzer.analyze_monthly_trends()
    yearly_trends = trend_analyzer.analyze_yearly_trends()
    print("Monthly Trends:", monthly_trends)
    print("Yearly Trends:", yearly_trends)