def select_output_format(self):
        print("Select the desired output format:")
        print("1. PDF")
        print("2. DOCX")
        print("3. XLSX")
        print("4. CSV")
        print("5. PPTX")
        print("6. JPG")
        print("7. PNG")
        choice = input("Enter the number corresponding to your choice: ")
        return self._map_choice_to_format(choice)