def main():
    hotel_manager = HotelManager()
    hotel_manager.manage_bookings()
    hotel_manager.allocate_rooms()
    hotel_manager.schedule_staff()
    hotel_manager.manage_inventory()
    hotel_manager.customer_service()
    hotel_manager.marketing()
    hotel_manager.optimize_operations()
    hotel_manager.financial_report()