def display_menu(self):
        print("Welcome to the Budgeting Software")
        print("1. Add Income")
        print("2. Add Expense")
        print("3. Set Savings Goal")
        print("4. View Budget Summary")
        print("5. Visualize Budget Breakdown")
        print("6. Visualize Savings Progress")
        print("7. Save Data")
        print("8. Load Data")
        print("9. Exit")