def visualize_scale(self, scale):
        plt.figure(figsize=(12, 3))
        plt.plot(range(len(scale)), [1] * len(scale), 'ro', markersize=10)
        plt.title(f"Visualization of {scale} Scale")
        plt.xlabel("Notes")
        plt.ylabel("Presence")
        plt.xticks(range(len(scale)), scale)
        plt.yticks([])
        plt.grid(True, which='both', linestyle='--', linewidth=0.5)
        plt.axhline(0, color='black', linewidth=0.8)
        plt.show()