def main():
    game = Game()
    player1 = Player("ArtLover123")
    game.add_player(player1)
    artist1 = Artist("Vincent van Gogh", 1853, "Dutch")
    artwork1 = Artwork("Starry Night", artist1, 1889, "A famous painting by Vincent van Gogh.")
    artist1.add_artwork(artwork1)
    gallery1 = Gallery("Modern Art Gallery", "New York")
    player1.create_gallery(gallery1, game)
    player1.view_gallery("Modern Art Gallery")
    game.start_game()