def display_menu(self):
        print("\nOrganizer Pro Menu:")
        print("1. Add Task")
        print("2. Remove Task")
        print("3. Update Task")
        print("4. List Tasks")
        print("5. Generate Calendar View")
        print("6. Generate List View")
        print("7. Set Reminder")
        print("8. Generate Report")
        print("9. Exit")