	string text2;
	string text3;
	string text4;
	string text5;
	string text6;
	std::regex regex("^\d{1,2}.");
	std::smatch match;
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);
	std::cout << match.str() << "\n";
	std::regex_search(text1, match, regex);