	int result = 0;
	for (vector<int> l : lst) {
		if (result < l.size()) result = l.size();
	}
	return result;
}
"""
"""
#Question 21
#Question:
#You are given the function f(int N, vector<int> A)
#Your task is to fill A by N-1 zeros followed by N-1 ones such that:
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones is followed by zeros
#every adjacent pair of zeros is followed by ones
#every adjacent pair of ones