	std::queue<int> heap;
	std::queue<int> heapSort;
	std::sort(rawheap.begin(), rawheap.end());
	std::cout << rawheap << std::endl;
	for (unsigned int i = 0; i < rawheap.size(); i++) {
		std::cout << rawheap[i] << " " << (i + 1) << std::endl;
		std::cout << heap.empty() << std::endl;
		while (i > 0 && (i % 2 != 0 && (rawheap[i] > rawheap[(i - 1) / 2]) || (i % 2 == 0 && (rawheap[i] > rawheap[(i - 1) / 2] && (rawheap[i] > rawheap[((i - 1) / 2) - 1]))))){
			std::cout << rawheap[i] << " " << (i + 1) << std::endl;
			std::cout << (i - 1) / 2 << std::endl;
			std::cout << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[((i - 1) / 2) - 1] << std::endl;
			std::cout << heap.empty() << std::endl;
			std::cout << heapSort.empty() << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[i] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[((i - 1) / 2) - 1] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[((i - 1) / 2) - 1] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2] << " " << rawheap[(i - 1) / 2] << std::endl;
			std::cout << rawheap[(i - 1) / 2]