	vector<int> res;
	testTup1.insert(testTup1.end(), testTup2.begin(), testTup2.end());
	return testTup1;
}
int main() {
	vector<int> testTup1, testTup2;
	testTup1.push_back(3);
	testTup1.push_back(4);
	testTup2.push_back(5);
	testTup2.push_back(6);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);
	testTup1 = concatenateNested(testTup1, testTup2);