	string match = "Found a match!";
	string notMatch = "Not matched!";
	string::iterator iter1, iter2; 
	for(iter1 = text.begin(); iter1 != text.end(); iter1++){ 
		if(*iter1 == 'a'){
			iter2 = iter1;
			iter2--;
			if(*iter2 == 'a'){
				iter2++;
				while(iter2 != iter1){
					if(*iter2 == 'b'){
						match = "Found a match!";
						return match;
					}
					iter2++;
				}
			}
		}
	}
	return notMatch;
}
/**
 * Write a function that matches a string that has an a followed by zero or more b's.
 * > textMatchZero(string("dc"))
 * string("Found a match!")
 * > textMatchZero(string("dcbb"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbb"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbba"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaac"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabb"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbb"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbcccc"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("dbbbbbaabbabbbbccccaaaa"))
 * string("Found a match!")
 * > textMatchZero(string("