	int low = 0;
	int high = itemList.size() - 1;
	while (low <= high) {
		int mid = (low + high) / 2;
		if (itemList[mid] == item) {
			return true;
		} else if (itemList[mid] < item) {
			low = mid + 1;
		} else {
			high = mid - 1;
		}
	}
	return false;
}
int main() {
	vector<int> testList{7, 8, 9, 10, 13};
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(16);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(17);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(18);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(19);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(20);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(21);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(22);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(23);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(24);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(25);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(26);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(27);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(28);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(29);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(30);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(31);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(32);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(33);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(34);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(35);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(36);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(37);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(38);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(39);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(40);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(41);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(42);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(43);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(44);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(45);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(46);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(47);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(48);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(49);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(50);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(51);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(52);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(53);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(54);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(55);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(56);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(57);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(58);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(59);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(60);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(61);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(62);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(63);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(64);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(65);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(66);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(67);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(68);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(69);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(70);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(71);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(72);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(73);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(74);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(75);
	cout << binarySearch(testList, 8) << endl;
	testList.push_back(76);
	cout << binarySearch(testList, 8) << endl;
	testList.push