	unordered_set<string> res;
	for (string s : t)
		res.insert(s);
	return res;
}
unordered_set<string> sortTuple(unordered_set<string> t) {
	string first = *t.begin();
	string last = *t.rbegin();
	string mid = "";
	while (1) {
		string tmp = first.back();
		first.pop_back();
		if (tmp == last[0]) {
			mid = tmp;
			break;
		}
	}
	string tmp = last.back();
	last.pop_back();
	string tmp2 = first.back();
	first.pop_back();
	string tmp3 = last.back();
	last.pop_back();
	string tmp4 = first.back();
	first.pop_back();
	string tmp5 = last.back();
	last.pop_back();
	string tmp6 = first.back();
	first.pop_back();
	string tmp7 = last.back();
	last.pop_back();
	string tmp8 = first.back();
	first.pop_back();
	string tmp9 = last.back();
	last.pop_back();
	string tmp10 = first.back();
	first.pop_back();
	string tmp11 = last.back();
	last.pop_back();
	string tmp12 = first.back();
	first.pop_back();
	string tmp13 = last.back();
	last.pop_back();
	string tmp14 = first.back();
	first.pop_back();
	string tmp15 = last.back();
	last.pop_back();
	string tmp16 = first.back();
	first.pop_back();
	string tmp17 = last.back();
	last.pop_back();
	string tmp18 = first.back();
	first.pop_back();
	string tmp19 = last.back();
	last.pop_back();
	string tmp20 = first.back();
	first.pop_back();
	string tmp21 = last.back();
	last.pop_back();
	string tmp22 = first.back();
	first.pop_back();
	string tmp23 = last.back();
	last.pop_back();
	string tmp24 = first.back();
	first.pop_back();
	string tmp25 = last.back();
	last.pop_back();
	string tmp26 = first.back();
	first.pop_back();
	string tmp27 = last.back();
	last.pop_back();
	string tmp28 = first.back();
	first.pop_back();
	string tmp29 = last.back();
	last.pop_back();
	string tmp30 = first.back();
	first.pop_back();
	string tmp31 = last.back();
	last.pop_back();
	string tmp32 = first.back();
	first.pop_back();
	string tmp33 = last.back();
	last.pop_back();
	string tmp34 = first.back();
	first.pop_back();
	string tmp35 = last.back();
	last.pop_back();
	string tmp36 = first.back();
	first.pop_back();
	string tmp37 = last.back();
	last.pop_back();
	string tmp38 = first.back();
	first.pop_back();
	string tmp39 = last.back();
	last.pop_back();
	string tmp40 = first.back();
	first.pop_back();
	string tmp41 = last.back();
	last.pop_back();
	string tmp42 = first.back();
	first.pop_back();
	string tmp43 = last.back();
	last.pop_back();
	string tmp44 = first.back();
	first.pop_back();
	string tmp45 = last.back();
	last.pop_back();
	string tmp46 = first.back();
	first.pop_back();
	string tmp47 = last.back();
	last.pop_back();
	string tmp48 = first.back();
	first.pop_back();
	string tmp49 = last.back();
	last.pop_back();
	string tmp50 = first.back();
	first.pop_back();
	string tmp51 = last.back();
	last.pop_back();
	string tmp52 = first.back();
	first.pop_back();
	string tmp53 = last.back();
	last.pop_back();
	string tmp54 = first.back();
	first.pop_back();
	string tmp55 = last.back();
	last.pop_back();
	string tmp56 = first.back();
	first.pop_back();
	string tmp57 = last.back();
	last.pop_back();
	string tmp58 = first.back();
	first.pop_back();
	string tmp59 = last.back();
	last.pop_back();
	string tmp60 = first.back();
	first.pop_back();
	string tmp61 = last.back();
	last.pop_back();
	string tmp62 = first.back();
	first.pop_back();
	string tmp63 = last.back();
	last.pop_back();
	string tmp64 = first.back();
	first.pop_back();
	string tmp65 = last.back();
	last.pop_back();
	string tmp66 = first.back();
	first.pop_back();
	string tmp67 = last.back();
	last.pop_back();
	string tmp68 = first.back();
	first.pop_back();
	string tmp69 = last.back();
	last.pop_back();
	string tmp70 = first.back();
	first.pop_back();
	string tmp71 = last.back();
	last.pop_back();
	string tmp72 = first.back();
	first.pop_back();
	string tmp73 = last.back();
	last.pop_back();
	string tmp74 = first.back();
	first.pop_back();
	string tmp75 = last.back();
	last.pop_back();
	string tmp76 = first.back();
	first.pop_back();
	string tmp77 = last.back();
	last.pop_back();
	string tmp78 = first.back();
	first.pop_back();
	string tmp79 = last.back();
	last.pop_back();
	string tmp80 = first.back();
	first.pop_back();
	string tmp81 = last.back();
	last.pop_back();
	string tmp82 = first.back();
	first.pop_back();
	string tmp83 = last.back();
	last.pop_back();
	string tmp84 = first.back();
	first.pop_back();
	string tmp85 = last.back();
	last.pop_back();
	string tmp86 = first.back();
	first.pop_back();
	string tmp87 = last.back();
	last.pop_back();
	string tmp88 = first.back();
	first.pop_back();
	string tmp89 = last.back();
	last.pop_back();
	string tmp90 = first.back();
	first.pop_back();
	string tmp91 = last.back();
	last.pop_back();
	string tmp92 = first.back();
	first.pop_back();
