	vector<vector<int>> final_list;
	for(int i=strtVal; i<=stopVal; i++){
		final_list.push_back({i, i});
	}
	for(int i=0; i<testList.size(); i++){
		final_list.remove(testList[i]);
	}
	return final_list;
}
int main() {
	vector<vector<int>> testList{ {6, 9}, {15, 34}, {48, 70} };
	testList = extractMissing(testList, 2, 100);
	testList = extractMissing(testList, 5, 60);
	testList = extractMissing(testList, 1, 52);
	testList = extractMissing(testList, 1, 52);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList, 8, 8);
	testList = extractMissing(testList