	std::vector<std::vector<std::vector<double>>> res;
	std::vector<std::vector<double>> curr_poly;
	curr_poly.push_back({startx, starty});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({startx - radius, starty});
	curr_poly.push_back({startx - radius, starty - radius});
	curr_poly.push_back({startx, starty - radius});
	curr_poly.push_back({startx + radius, starty - radius});
	curr_poly.push_back({startx + radius, starty});
	curr_poly.push_back({endx, starty});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({startx + radius, starty + radius});
	curr_poly.push_back({startx + radius, endy});
	curr_poly.push_back({startx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({endx - radius, endy});
	curr_poly.push_back({endx - radius, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({startx + radius, starty + radius});
	curr_poly.push_back({startx + radius, endy});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({startx + radius, starty + radius});
	curr_poly.push_back({startx + radius, endy});
	curr_poly.push_back({startx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({endx - radius, endy});
	curr_poly.push_back({endx - radius, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({startx + radius, starty + radius});
	curr_poly.push_back({startx + radius, endy});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({startx + radius, starty + radius});
	curr_poly.push_back({startx + radius, endy});
	curr_poly.push_back({startx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({startx - radius, endy});
	curr_poly.push_back({startx - radius, starty + radius});
	curr_poly.push_back({startx, starty + radius});
	curr_poly.push_back({endx, starty + radius});
	curr_poly.push_back({endx, endy});
	curr_poly.push_back({endx - radius, endy});
	curr_poly.push_back({endx - radius, starty + radius});
	curr_poly.push_back({endx, starty + radius});
