def create_teams(self):
        team1 = Team("Team Alpha")
        team2 = Team("Team Omega")
        self.teams.append(team1)
        self.teams.append(team2)
        char1 = Character("Warrior", 100, 20, 10, [Ability("Slash", "damage")])
        char2 = Character("Mage", 80, 15, 5, [Ability("Fireball", "fireball")])
        char3 = Character("Archer", 90, 18, 8, [Ability("Arrow Rain", "damage")])
        char4 = Character("Knight", 110, 22, 12, [Ability("Shield Bash", "shield")])
        char5 = Character("Sorcerer", 75, 17, 6, [Ability("Lightning", "lightning")])
        char6 = Character("Rogue", 85, 19, 7, [Ability("Backstab", "backstab")])
        team1.add_character(char1)
        team1.add_character(char2)
        team1.add_character(char3)
        team2.add_character(char4)
        team2.add_character(char5)
        team2.add_character(char6)