def plot_skills(self):
        skills = self.character.get_skills()
        names = list(skills.keys())
        levels = list(skills.values())
        plt.figure(figsize=(10, 5))
        plt.bar(names, levels, color=f'green')
        plt.title(f'Character Skills')
        plt.xlabel(f'Skills')
        plt.ylabel(f'Levels')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()