def plot_attributes(self):
        attributes = self.character.get_attributes()
        names = list(attributes.keys())
        values = list(attributes.values())
        plt.figure(figsize=(10, 5))
        plt.bar(names, values, color='blue')
        plt.title('Character Attributes')
        plt.xlabel('Attributes')
        plt.ylabel('Values')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()