def main():
    task_manager = TaskManager()
    scheduler = Scheduler()
    notification_manager = NotificationManager()
    visual_overview = VisualOverview()
    # Example usage
    task_manager.add_task("Complete project report", "2023-10-15", "High")
    task_manager.add_task("Prepare presentation", "2023-10-16", "Medium")
    task_manager.set_priority("Complete project report", "Urgent")
    scheduler.allocate_time("Complete project report", "09:00", "11:00")
    scheduler.allocate_time("Prepare presentation", "11:30", "12:30")
    notification_manager.send_reminder("Complete project report")
    notification_manager.send_notification("Prepare presentation")
    visual_overview.generate_overview(task_manager.get_all_tasks(), scheduler.get_schedule())
    visual_overview.display_overview()