def display_menu(self):
        print("\nQuest Tracker Plus Menu:")
        print("1. Add Quest")
        print("2. Update Quest")
        print("3. Complete Quest")
        print("4. View Progress")
        print("5. Get Quest Hint")
        print("6. Get Quest Strategy")
        print("7. Set Reminder")
        print("8. Add Category")
        print("9. Assign Tag")
        print("0. Exit")